### ISSUE TITLE
Try catch blocks

### ISSUE THREAD

**Issue by JordanRad** [Exordium-Project/e-shop#14]
Whenever you see an **await** withing a function, please surround it with a try-catch block as it follows:

```
try {
   let result = await myService.get()
} catch(err){
   console.log(err)
}
```

**Comment by petya0111** [comment]
@Arabadzhiew  We can use this style of async-await and catch block

async function findUserById(id) {
  const user = await database.getUserById(id)
    .catch(error => {
      // do something with error
    });

  return user;
}


reference https://www.robinwieruch.de/javascript-async-await-without-try-catch/
